version: "0.9.1-{build}"
environment:
  matrix:
    - job_name: Windows x64
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: Linux x64
      appveyor_build_worker_image: Ubuntu
configuration:
  - Release
install:
  - cmd: cp cmake/CMakePresets.json .
  - sh: |
      [ "$SKIP_LINUX" == "true" ] && echo "-- Skipping Linux --" && exit
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      echo "== Installing dependencies ==" && sudo apt -qq update && sudo apt -qq install -y gcc-10 g++-10 xorg-dev
      cp cmake/CMakePresets.json .
build_script: cmake -P cmake/package.cmake
test_script:
  - sh: cd build/package/Release; ctest || exit 1; examples/dibs-example
  - cmd: |
      cd build/package/Release
      ctest -C Release || exit 1
after_build:
  - cmd: move "build\package\dibs-Windows-x64.zip" "dibs-v0.9.1-Windows-x64.zip"
  - sh: mv build/package/dibs-Linux-x64.tar.gz dibs-v0.9.1-Linux-x64.tar.gz
for:
  - matrix:
      only:
        - job_name: Windows x64
    artifacts:
      - path: dibs-v0.9.1-Windows-x64.zip
  - matrix:
      only:
        - job_name: Linux x64
    artifacts:
      - path: dibs-v0.9.1-Linux-x64.tar.gz
matrix:
  fast_finish: true
skip_branch_with_pr: true
deploy:
  - provider: GitHub
    tag: "v0.9.1"
    release: "dibs-v0.9.1"
    description: "Instigator: Appveyor CI script"
    auth_token:
      secure: Q4k4QeaxqXS7TIPI+dKfG8m2a8RTpP9G4sbpxhA9isKu3PgZywKwy5+ecPXyS7A5
    artifact: dibs-v0.9.1-Windows-x64.zip,dibs-v0.9.1-Linux-x64.tar.gz
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
