name: release
on:
  push:
    tags: "v*.*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            install: choco install ninja
            extension: zip
          - os: ubuntu-latest
            install: sudo apt install -yqq ninja-build xorg-dev
            extension: tar.gz
    steps:
      - uses: actions/checkout@v2
      - name: install
        shell: bash
        run: ${{ matrix.install }}
      - name: build
        shell: bash
        run: |
          cp cmake/CMakePresets.json .
          cmake -P cmake/package.cmake
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          files: build/package/*.${{ matrix.extension }}
          draft: true
